### ISSUE TITLE
Question : We need to use postMessage API and want to use window Obj

### ISSUE THREAD

**Issue by gs-akhan** [zendesk/demo_apps#70]
```
(function(window) {
//My app here
window.open();
})(this);
```

Is this allowed ? thanks

**Comment by gs-akhan** [comment]
And extending to this question, I am hoping we are not allowed to hotlink any external JS files in handlebar partials ? 
Please let me know if that is allowed thanks ?

**Comment by atroche** [comment]
@gs-akhan can you tell us more about what you're trying to do? and a little more context about what your app is and what you're trying to do?

**Comment by princemaple** [comment]
iframe app is the closest they can get, basically.

**Comment by danielbreves** [comment]
@gs-akhan, accessing the window object from an app is not allowed. However, the framework does provide a wrapper for the postMessage API. Have a look at our documentation for [Iframes in Apps](https://developer.zendesk.com/apps/docs/agent/iframes_in_apps) and let us know if it solves it for you.

**Comment by gs-akhan** [comment]
@atroche @danielbreves  
We want to open window from the open for oauth purpose and then window which completes ouath, I send post message to zendesk app to reload itself..  This is the usecase. 
And is hot linking external JS files in handlebar templates allowed, ?

Thanks

**Comment by gs-akhan** [comment]
Any one on this ? thanks .
Otherwise I need to make our app as an "iframe" and then just include it in the handlebars template.

I can also make use of external JS libraries as well. If I am thinking correctly .

**Comment by atroche** [comment]
Hi @gs-akhan, you're going to have to use an iframe. Let us know how it goes!

**Comment by danielbreves** [comment]
Hot linking external JS files in app templates is not allowed. But, of course, you can do whatever you like from an iframe. Make sure you include your iframe using the Handlebars [framework helper](https://developer.zendesk.com/apps/docs/agent/templates#iframe-url) `{{ iframe "srcUrl" }}`, as that will enable cross-frame communication with the [SDK](https://developer.zendesk.com/apps/docs/agent/iframes_in_apps).
